version: '3'
services:
  php-environment:
    container_name: php
    build:
      context: ./project
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./project:/var/www/html/
    ports:
      - 9000:80
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
      MYSQL_DATABASE: project
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8081:80
